

server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:401/financial_tracker
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    problemdetails:
      enabled: true
  liquibase:
    change-log: classpath:db/master.xml
  application:
    name: FinTracker

logging:
  level:
    org:
      springframework.security: TRACE
      hibernate:
        sql: DEBUG
        type.descriptor.sql.basicBinder: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
