server:
  port: 8081

spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:401/financial_tracker
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    problemdetails:
      enabled: true